In [2]:
from pathlib import Path

import pandas as pd
import numpy as np

In [5]:
try:
    import common
    DATA = common.dataDirectory()
except ImportError:
    DATA = Path().resolve() / 'data'

In [40]:
techMat_csv = DATA / 'hw6_tech_matrix.csv'
fdQ2_csv = DATA / 'hw6_fd_q2.csv'
fdQ5_csv = DATA / 'hw6_fd_q5.csv'

In [47]:
techMat = pd.read_csv(techMat_csv)
fdQ2 = pd.read_csv(fdQ2_csv)
fdQ5= pd.read_csv(fdQ5_csv)

In [48]:
techMat.head(5)

,Linear Space,Unit,Transport Person/ employee,"Diesel, at refinery","Transport, barge, average fuel mix","Transport, combination truck, average fuel mix","Transport, ocean freighter, average fuel mix","Transport, pipeline, unspecified petroleum products","Transport, train, diesel powered","Crude oil, extracted",...,"Electricity, nuclear, at power plant","Electricity, residual fuel oil, at power plant","Transport, combination truck, diesel powered","Natural gas, processed, at plant","Natural gas, extracted","Bituminous coal, at mine [from row 30]","Lignite coal, at surface mine [row 32]","Lignite coal, combusted in industrial boiler[row 32]","Fuel grade uranium, at regional storage [row 34]","Bituminous coal, combusted in industrial boiler[34]"
0,Transport Person/employee,p*km,1.000000,0.0000,0.0,0,0,0.0,0.000000,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000
1,"Diesel, at refinery",m^3,-0.004277,0.2523,0.0,0,0,0.0,-0.006482,0.0,...,0.0,0.000000,-0.02722,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000
2,"Transport, barge, average fuel mix",t*km,-0.001334,0.0000,1.0,0,0,0.0,0.000000,0.0,...,0.0,-0.007487,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,-0.126600
3,"Transport, combination truck, average fuel mix",t*km,-0.001379,0.0000,0.0,1,0,0.0,0.000000,0.0,...,0.0,-0.001382,0.00000,0.0,0.0,0.0,0.0,-0.01101,-27.9,-0.006759
4,"Transport, ocean freighter, average fuel mix",t*km,-0.009426,0.0000,0.0,0,1,0.0,0.000000,0.0,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000

In [60]:
techMat_del = techMat.drop(['Linear Space','Unit'], 1)

In [61]:
techMat_del

,Transport Person/ employee,"Diesel, at refinery","Transport, barge, average fuel mix","Transport, combination truck, average fuel mix","Transport, ocean freighter, average fuel mix","Transport, pipeline, unspecified petroleum products","Transport, train, diesel powered","Crude oil, extracted","Electricity, at grid (US, 2010)","Liquefied petroleum gas, combusted in industrial boiler",...,"Electricity, nuclear, at power plant","Electricity, residual fuel oil, at power plant","Transport, combination truck, diesel powered","Natural gas, processed, at plant","Natural gas, extracted","Bituminous coal, at mine [from row 30]","Lignite coal, at surface mine [row 32]","Lignite coal, combusted in industrial boiler[row 32]","Fuel grade uranium, at regional storage [row 34]","Bituminous coal, combusted in industrial boiler[34]"
0,1.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
1,-0.004277,0.252300,0.00,0,0,0.0000,-0.006482,0.000000,0.000000,0.000000,...,0.000000,0.000000,-0.02722,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
2,-0.001334,0.000000,1.00,0,0,0.0000,0.000000,0.000000,0.000000,-0.028430,...,0.000000,-0.007487,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,-0.126600
3,-0.001379,0.000000,0.00,1,0,0.0000,0.000000,0.000000,0.000000,-0.005245,...,0.000000,-0.001382,0.00000,0.000000,0.000000,0.000000,0.000000,-0.01101,-27.90000,-0.006759
4,-0.009426,0.000000,0.00,0,1,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
5,-0.013900,0.000000,0.00,0,0,1.0000,0.000000,0.000000,0.000000,-0.041310,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
6,-0.002573,0.000000,0.00,0,0,0.0000,1.000000,0.000000,0.000000,-0.003355,...,0.000000,-0.000884,0.00000,0.000000,0.000000,0.000000,0.000000,-0.00103,0.00000,-1.043000
7,0.000000,-1.018000,0.00,0,0,0.0000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
8,0.000000,-0.143090,0.00,0,0,-0.0149,0.000000,-0.039010,1.000000,0.000000,...,0.000000,0.000000,0.00000,-0.015719,-0.039000,-0.038700,-0.053300,0.00000,-4080.00000,0.000000
9,0.000000,-0.001149,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
10,0.000000,-0.011110,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,-0.025480,-0.032799,-0.000162,-0.000251,0.00000,-184.00000,0.000000
11,0.000000,-0.027229,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,-0.000037,-0.000798,-0.000870,-0.001450,0.00000,-0.11099,0.000000
12,0.000000,-0.000288,-0.22,0,0,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
13,0.000000,-0.000958,-0.78,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
14,0.000000,-0.489890,0.00,0,1,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,-7.89000,0.000000
15,0.000000,-4.409000,0.00,0,9,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,-71.00000,0.000000
16,0.000000,-0.652200,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
17,0.000000,0.037170,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
18,0.000000,0.570100,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
19,0.000000,0.112500,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
20,0.000000,0.049080,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
21,0.000000,0.059590,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
22,0.000000,0.051450,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
23,0.000000,1.000000,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
24,0.000000,0.061170,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
25,0.000000,0.051830,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,-0.263390,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
26,0.000000,0.000000,0.00,0,0,0.0000,0.000000,-0.001293,0.000000,0.000000,...,0.000000,0.000000,0.00000,-0.000037,-0.001290,0.000000,-0.015000,0.00000,-20.60000,0.000000
27,0.000000,0.000000,0.00,0,0,0.0000,0.000000,-0.000684,0.000000,0.000000,...,0.000000,0.000000,0.00000,-0.000035,-0.000684,0.000000,-0.001410,0.00000,0.00000,0.000000
28,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,-0.411490,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
29,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,-0.012450,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
30,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,-0.019000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
31,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,-0.244600,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
32,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,-0.198200,0.000000,...,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
33,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,-0.003532,0.000000,...,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
34,0.000000,0.000000,0.00,1,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
35,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000
36,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,-0.740900,1.000000,0.000000,0.000000,0.00000,0.00000,0.000000
37,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,NaN,0.000000,1.000000,0.000000,0.00000,0.00000,1.000000
38,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,NaN,0.000000,0.000000,1.000000,-1.00000,0.00000,0.000000
39,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,NaN,0.000000,0.000000,-0.000362,1.00000,0.00000,0.000000
40,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,-0.000003,0.000000,0.00000,NaN,0.000000,0.000000,0.000000,0.00000,1.00000,0.000000
41,0.000000,0.000000,0.00,0,0,0.0000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,NaN,0.000000,0.000000,0.000000,0.00000,-22.70000,1.000000

In [59]:
techMat_del.head(5)

,Transport Person/ employee,"Diesel, at refinery","Transport, barge, average fuel mix","Transport, combination truck, average fuel mix","Transport, ocean freighter, average fuel mix","Transport, pipeline, unspecified petroleum products","Transport, train, diesel powered","Crude oil, extracted","Electricity, at grid (US, 2010)","Liquefied petroleum gas, combusted in industrial boiler",...,"Electricity, nuclear, at power plant","Electricity, residual fuel oil, at power plant","Transport, combination truck, diesel powered","Natural gas, processed, at plant","Natural gas, extracted","Bituminous coal, at mine [from row 30]","Lignite coal, at surface mine [row 32]","Lignite coal, combusted in industrial boiler[row 32]","Fuel grade uranium, at regional storage [row 34]","Bituminous coal, combusted in industrial boiler[34]"
1,-0.004277,0.2523,0.0,0,0,0.0,-0.006482,0.0,0.0,0.000000,...,0.0,0.000000,-0.02722,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000
2,-0.001334,0.0000,1.0,0,0,0.0,0.000000,0.0,0.0,-0.028430,...,0.0,-0.007487,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,-0.126600
3,-0.001379,0.0000,0.0,1,0,0.0,0.000000,0.0,0.0,-0.005245,...,0.0,-0.001382,0.00000,0.0,0.0,0.0,0.0,-0.01101,-27.9,-0.006759
4,-0.009426,0.0000,0.0,0,1,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000
5,-0.013900,0.0000,0.0,0,0,1.0,0.000000,0.0,0.0,-0.041310,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000

In [32]:
techMat_del = techMat.drop(['Linear Space','Unit'], 1)

KeyError: "['Linear Space' 'Unit'] not found in axis"

In [26]:
techMat_del.head(5)

,Transport Person/ employee,"Diesel, at refinery","Transport, barge, average fuel mix","Transport, combination truck, average fuel mix","Transport, ocean freighter, average fuel mix","Transport, pipeline, unspecified petroleum products","Transport, train, diesel powered","Crude oil, extracted","Electricity, at grid (US, 2010)","Liquefied petroleum gas, combusted in industrial boiler",...,"Electricity, nuclear, at power plant","Electricity, residual fuel oil, at power plant","Transport, combination truck, diesel powered","Natural gas, processed, at plant","Natural gas, extracted","Bituminous coal, at mine [from row 30]","Lignite coal, at surface mine [row 32]","Lignite coal, combusted in industrial boiler[row 32]","Fuel grade uranium, at regional storage [row 34]","Bituminous coal, combusted in industrial boiler[34]"
0,1.000000,0.0000,0.0,0,0,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000
1,-0.004277,0.2523,0.0,0,0,0.0,-0.006482,0.0,0.0,0.000000,...,0.0,0.000000,-0.02722,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000
2,-0.001334,0.0000,1.0,0,0,0.0,0.000000,0.0,0.0,-0.028430,...,0.0,-0.007487,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,-0.126600
3,-0.001379,0.0000,0.0,1,0,0.0,0.000000,0.0,0.0,-0.005245,...,0.0,-0.001382,0.00000,0.0,0.0,0.0,0.0,-0.01101,-27.9,-0.006759
4,-0.009426,0.0000,0.0,0,1,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.000000,0.00000,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000

In [63]:
techMat_del = techMat_del.to_numpy()

In [65]:
techMat_del

array([[ 1.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
         0.0000e+00,  0.0000e+00],
       [-4.2769e-03,  2.5230e-01,  0.0000e+00, ...,  0.0000e+00,
         0.0000e+00,  0.0000e+00],
       [-1.3340e-03,  0.0000e+00,  1.0000e+00, ...,  0.0000e+00,
         0.0000e+00, -1.2660e-01],
       ...,
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  1.0000e+00,
         0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
         1.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
        -2.2700e+01,  1.0000e+00]])